name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: esp32

    steps:
    - uses: actions/checkout@v3

    - name: Make push
      run: make push

 
